apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint
  # these are replica set labels
  labels:
    purpose: taint-demo
    project: robomart
spec:
  replicas: 1
  selector:
  # these labels are used to select pods
    matchLabels:
      purpose: taint-demo
      project: robomart
  # pod definition
  template:
    metadata:
      labels:
        purpose: taint-demo
        project: robomart
    spec:
      containers:
      - name: nginx
        image: nginx:mainline-alpine3.23

